version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - h2
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/testdb
    command: ["./wait-for-services.sh", "mongodb:27017", "h2:8082"]

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  h2:
    image: jesperdj/h2:latest
    ports:
      - "9092:9092"
      - "8082:8082"
    volumes:
      - h2-data:/opt/h2-data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  h2-data:





